#![doc = "Peripheral access API for STM32WL33 microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 2;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
extern "C" {
    fn Flash();
    fn RCC();
    fn PVD();
    fn I2C1();
    fn I2C2();
    fn SPI1();
    fn SPI3();
    fn USART();
    fn LPUART();
    fn TIM2();
    fn RTC();
    fn ADC();
    fn AES();
    fn GPIOA();
    fn GPIOB();
    fn DMA();
    fn LPAWUR();
    fn COMP();
    fn MR_SUBG_BUSY();
    fn MR_SUBG();
    fn TX_RX_SEQUENCE();
    fn CPU_WKUP();
    fn SUBG_WKUP();
    fn DAC();
    fn TIM16();
    fn LCD();
    fn LCSC();
    fn LC_ACTIVITY();
}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    _handler: unsafe extern "C" fn(),
    _reserved: u32,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[link_section = ".vector_table.interrupts"]
#[no_mangle]
pub static __INTERRUPTS: [Vector; 30] = [
    Vector { _handler: Flash },
    Vector { _handler: RCC },
    Vector { _handler: PVD },
    Vector { _handler: I2C1 },
    Vector { _handler: I2C2 },
    Vector { _handler: SPI1 },
    Vector { _reserved: 0 },
    Vector { _handler: SPI3 },
    Vector { _handler: USART },
    Vector { _handler: LPUART },
    Vector { _handler: TIM2 },
    Vector { _handler: RTC },
    Vector { _handler: ADC },
    Vector { _handler: AES },
    Vector { _reserved: 0 },
    Vector { _handler: GPIOA },
    Vector { _handler: GPIOB },
    Vector { _handler: DMA },
    Vector { _handler: LPAWUR },
    Vector { _handler: COMP },
    Vector {
        _handler: MR_SUBG_BUSY,
    },
    Vector { _handler: MR_SUBG },
    Vector {
        _handler: TX_RX_SEQUENCE,
    },
    Vector { _handler: CPU_WKUP },
    Vector {
        _handler: SUBG_WKUP,
    },
    Vector { _handler: DAC },
    Vector { _handler: TIM16 },
    Vector { _handler: LCD },
    Vector { _handler: LCSC },
    Vector {
        _handler: LC_ACTIVITY,
    },
];
#[doc = r"Enumeration of all the interrupts."]
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
#[repr(u16)]
pub enum Interrupt {
    #[doc = "0 - Non-volatile memory (flash) controller"]
    Flash = 0,
    #[doc = "1 - Reset and Clock Controller"]
    RCC = 1,
    #[doc = "2 - PVD / BORH"]
    PVD = 2,
    #[doc = "3 - I2C1 interrupt"]
    I2C1 = 3,
    #[doc = "4 - I2C2 interrupt"]
    I2C2 = 4,
    #[doc = "5 - SPI1 interrupt"]
    SPI1 = 5,
    #[doc = "7 - SPI3 interrupt"]
    SPI3 = 7,
    #[doc = "8 - USART interrupt"]
    USART = 8,
    #[doc = "9 - LPUART interrupt"]
    LPUART = 9,
    #[doc = "10 - TIM2 interrupt"]
    TIM2 = 10,
    #[doc = "11 - RTC interrupt"]
    RTC = 11,
    #[doc = "12 - ADC interrupt"]
    ADC = 12,
    #[doc = "13 - AES interrupt"]
    AES = 13,
    #[doc = "15 - GPIOA interrupt"]
    GPIOA = 15,
    #[doc = "16 - GPIOB interrupt"]
    GPIOB = 16,
    #[doc = "17 - DMA interrupt"]
    DMA = 17,
    #[doc = "18 - LPAWUR interrupt"]
    LPAWUR = 18,
    #[doc = "19 - Comp interrupt through SYSCFG"]
    COMP = 19,
    #[doc = "20 - MR_SUBG Busy interrupt"]
    MR_SUBG_BUSY = 20,
    #[doc = "21 - MR_SUBG interrupt"]
    MR_SUBG = 21,
    #[doc = "22 - MR_SUBG TX/RX Sequence interrupt"]
    TX_RX_SEQUENCE = 22,
    #[doc = "23 - CPU Wakeup interrupt"]
    CPU_WKUP = 23,
    #[doc = "24 - SUBG Wakeup interrupt"]
    SUBG_WKUP = 24,
    #[doc = "25 - DAC interrupt"]
    DAC = 25,
    #[doc = "26 - TIM16 interrupt"]
    TIM16 = 26,
    #[doc = "27 - LCD interrupt"]
    LCD = 27,
    #[doc = "28 - LCSC interrupt"]
    LCSC = 28,
    #[doc = "29 - LCSC LC_ACTIVITY interrupt"]
    LC_ACTIVITY = 29,
}
unsafe impl cortex_m::interrupt::InterruptNumber for Interrupt {
    #[inline(always)]
    fn number(self) -> u16 {
        self as u16
    }
}
#[doc = "ADC address block description"]
pub type Adc = crate::Periph<adc::RegisterBlock, 0x4100_6000>;
impl core::fmt::Debug for Adc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Adc").finish()
    }
}
#[doc = "ADC address block description"]
pub mod adc;
#[doc = "AES"]
pub type Aes = crate::Periph<aes::RegisterBlock, 0x4890_0000>;
impl core::fmt::Debug for Aes {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Aes").finish()
    }
}
#[doc = "AES"]
pub mod aes;
#[doc = "CRC"]
pub type Crc = crate::Periph<crc::RegisterBlock, 0x4820_0000>;
impl core::fmt::Debug for Crc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Crc").finish()
    }
}
#[doc = "CRC"]
pub mod crc;
#[doc = "COMP address block description"]
pub type Comp = crate::Periph<comp::RegisterBlock, 0x4000_9000>;
impl core::fmt::Debug for Comp {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Comp").finish()
    }
}
#[doc = "COMP address block description"]
pub mod comp;
#[doc = "DAC address block description"]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x4000_6000>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "DAC address block description"]
pub mod dac;
#[doc = "DBGMCU"]
pub type Dbgmcu = crate::Periph<dbgmcu::RegisterBlock, 0x4000_8000>;
impl core::fmt::Debug for Dbgmcu {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dbgmcu").finish()
    }
}
#[doc = "DBGMCU"]
pub mod dbgmcu;
#[doc = "DMAMUX address block description"]
pub type Dmamux = crate::Periph<dmamux::RegisterBlock, 0x4880_0000>;
impl core::fmt::Debug for Dmamux {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dmamux").finish()
    }
}
#[doc = "DMAMUX address block description"]
pub mod dmamux;
#[doc = "DMA address block description"]
pub type Dma = crate::Periph<dma::RegisterBlock, 0x4870_0000>;
impl core::fmt::Debug for Dma {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dma").finish()
    }
}
#[doc = "DMA address block description"]
pub mod dma;
#[doc = "DYNAMIC_REG"]
pub type DynamicReg = crate::Periph<dynamic_reg::RegisterBlock, 0x4900_0500>;
impl core::fmt::Debug for DynamicReg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("DynamicReg").finish()
    }
}
#[doc = "DYNAMIC_REG"]
pub mod dynamic_reg;
#[doc = "4kb addressable space"]
pub type FlashCtrl = crate::Periph<flash_ctrl::RegisterBlock, 0x4000_1000>;
impl core::fmt::Debug for FlashCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("FlashCtrl").finish()
    }
}
#[doc = "4kb addressable space"]
pub mod flash_ctrl;
#[doc = "GPIOA"]
pub type Gpioa = crate::Periph<gpioa::RegisterBlock, 0x4800_0000>;
impl core::fmt::Debug for Gpioa {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpioa").finish()
    }
}
#[doc = "GPIOA"]
pub mod gpioa;
#[doc = "GPIOB"]
pub type Gpiob = crate::Periph<gpiob::RegisterBlock, 0x4810_0000>;
impl core::fmt::Debug for Gpiob {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpiob").finish()
    }
}
#[doc = "GPIOB"]
pub mod gpiob;
#[doc = "I2C1"]
pub type I2c1 = crate::Periph<i2c1::RegisterBlock, 0x4100_0000>;
impl core::fmt::Debug for I2c1 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c1").finish()
    }
}
#[doc = "I2C1"]
pub mod i2c1;
#[doc = "I2C2"]
pub type I2c2 = crate::Periph<i2c2::RegisterBlock, 0x4100_1000>;
impl core::fmt::Debug for I2c2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("I2c2").finish()
    }
}
#[doc = "I2C2"]
pub mod i2c2;
#[doc = "IWDG"]
pub type Iwdg = crate::Periph<iwdg::RegisterBlock, 0x4000_3000>;
impl core::fmt::Debug for Iwdg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Iwdg").finish()
    }
}
#[doc = "IWDG"]
pub mod iwdg;
#[doc = "LCD"]
pub type Lcd = crate::Periph<lcd::RegisterBlock, 0x4000_7000>;
impl core::fmt::Debug for Lcd {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcd").finish()
    }
}
#[doc = "LCD"]
pub mod lcd;
#[doc = "LPUART"]
pub type Lpuart = crate::Periph<lpuart::RegisterBlock, 0x4100_5000>;
impl core::fmt::Debug for Lpuart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpuart").finish()
    }
}
#[doc = "LPUART"]
pub mod lpuart;
#[doc = "LCSC"]
pub type Lcsc = crate::Periph<lcsc::RegisterBlock, 0x4000_a000>;
impl core::fmt::Debug for Lcsc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lcsc").finish()
    }
}
#[doc = "LCSC"]
pub mod lcsc;
#[doc = "LPAWUR"]
pub type Lpawur = crate::Periph<lpawur::RegisterBlock, 0x4900_1000>;
impl core::fmt::Debug for Lpawur {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Lpawur").finish()
    }
}
#[doc = "LPAWUR"]
pub mod lpawur;
#[doc = "MISC"]
pub type Misc = crate::Periph<misc::RegisterBlock, 0x4900_0700>;
impl core::fmt::Debug for Misc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Misc").finish()
    }
}
#[doc = "MISC"]
pub mod misc;
#[doc = "MR_SUBG"]
pub type MrSubg = crate::Periph<mr_subg::RegisterBlock, 0x4900_0000>;
impl core::fmt::Debug for MrSubg {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MrSubg").finish()
    }
}
#[doc = "MR_SUBG"]
pub mod mr_subg;
#[doc = "PWRC"]
pub type Pwrc = crate::Periph<pwrc::RegisterBlock, 0x4850_0000>;
impl core::fmt::Debug for Pwrc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Pwrc").finish()
    }
}
#[doc = "PWRC"]
pub mod pwrc;
#[doc = "RCC"]
pub type Rcc = crate::Periph<rcc::RegisterBlock, 0x4840_0000>;
impl core::fmt::Debug for Rcc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rcc").finish()
    }
}
#[doc = "RCC"]
pub mod rcc;
#[doc = "RETAINED"]
pub type Retained = crate::Periph<retained::RegisterBlock, 0x4900_0780>;
impl core::fmt::Debug for Retained {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Retained").finish()
    }
}
#[doc = "RETAINED"]
pub mod retained;
#[doc = "RNG"]
pub type Rng = crate::Periph<rng::RegisterBlock, 0x4860_0000>;
impl core::fmt::Debug for Rng {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rng").finish()
    }
}
#[doc = "RNG"]
pub mod rng;
#[doc = "RTC"]
pub type Rtc = crate::Periph<rtc::RegisterBlock, 0x4000_4000>;
impl core::fmt::Debug for Rtc {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Rtc").finish()
    }
}
#[doc = "RTC"]
pub mod rtc;
#[doc = "SPI"]
pub type Spi = crate::Periph<spi::RegisterBlock, 0x4100_2000>;
impl core::fmt::Debug for Spi {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi").finish()
    }
}
#[doc = "SPI"]
pub mod spi;
#[doc = "SPI3"]
pub type Spi3 = crate::Periph<spi3::RegisterBlock, 0x4100_7000>;
impl core::fmt::Debug for Spi3 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Spi3").finish()
    }
}
#[doc = "SPI3"]
pub mod spi3;
#[doc = "SYSTEM_CTRL"]
pub type SystemCtrl = crate::Periph<system_ctrl::RegisterBlock, 0x4000_0000>;
impl core::fmt::Debug for SystemCtrl {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("SystemCtrl").finish()
    }
}
#[doc = "SYSTEM_CTRL"]
pub mod system_ctrl;
#[doc = "SWITCHABLE"]
pub type Switchable = crate::Periph<switchable::RegisterBlock, 0x4900_1040>;
impl core::fmt::Debug for Switchable {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Switchable").finish()
    }
}
#[doc = "SWITCHABLE"]
pub mod switchable;
#[doc = "STATUS"]
pub type Status = crate::Periph<status::RegisterBlock, 0x4900_0600>;
impl core::fmt::Debug for Status {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Status").finish()
    }
}
#[doc = "STATUS"]
pub mod status;
#[doc = "STATIC"]
pub type Static = crate::Periph<static_::RegisterBlock, 0x4900_0400>;
impl core::fmt::Debug for Static {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Static").finish()
    }
}
#[doc = "STATIC"]
pub mod static_;
#[doc = "TIM16 address block description"]
pub type Tim16 = crate::Periph<tim16::RegisterBlock, 0x4000_5000>;
impl core::fmt::Debug for Tim16 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim16").finish()
    }
}
#[doc = "TIM16 address block description"]
pub mod tim16;
#[doc = "TIM2 address block description"]
pub type Tim2 = crate::Periph<tim2::RegisterBlock, 0x4000_2000>;
impl core::fmt::Debug for Tim2 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Tim2").finish()
    }
}
#[doc = "TIM2 address block description"]
pub mod tim2;
#[doc = "USART"]
pub type Usart = crate::Periph<usart::RegisterBlock, 0x4100_4000>;
impl core::fmt::Debug for Usart {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Usart").finish()
    }
}
#[doc = "USART"]
pub mod usart;
#[no_mangle]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "ADC"]
    pub adc: Adc,
    #[doc = "AES"]
    pub aes: Aes,
    #[doc = "CRC"]
    pub crc: Crc,
    #[doc = "COMP"]
    pub comp: Comp,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "DBGMCU"]
    pub dbgmcu: Dbgmcu,
    #[doc = "DMAMUX"]
    pub dmamux: Dmamux,
    #[doc = "DMA"]
    pub dma: Dma,
    #[doc = "DYNAMIC_REG"]
    pub dynamic_reg: DynamicReg,
    #[doc = "FLASH_CTRL"]
    pub flash_ctrl: FlashCtrl,
    #[doc = "GPIOA"]
    pub gpioa: Gpioa,
    #[doc = "GPIOB"]
    pub gpiob: Gpiob,
    #[doc = "I2C1"]
    pub i2c1: I2c1,
    #[doc = "I2C2"]
    pub i2c2: I2c2,
    #[doc = "IWDG"]
    pub iwdg: Iwdg,
    #[doc = "LCD"]
    pub lcd: Lcd,
    #[doc = "LPUART"]
    pub lpuart: Lpuart,
    #[doc = "LCSC"]
    pub lcsc: Lcsc,
    #[doc = "LPAWUR"]
    pub lpawur: Lpawur,
    #[doc = "MISC"]
    pub misc: Misc,
    #[doc = "MR_SUBG"]
    pub mr_subg: MrSubg,
    #[doc = "PWRC"]
    pub pwrc: Pwrc,
    #[doc = "RCC"]
    pub rcc: Rcc,
    #[doc = "RETAINED"]
    pub retained: Retained,
    #[doc = "RNG"]
    pub rng: Rng,
    #[doc = "RTC"]
    pub rtc: Rtc,
    #[doc = "SPI"]
    pub spi: Spi,
    #[doc = "SPI3"]
    pub spi3: Spi3,
    #[doc = "SYSTEM_CTRL"]
    pub system_ctrl: SystemCtrl,
    #[doc = "SWITCHABLE"]
    pub switchable: Switchable,
    #[doc = "STATUS"]
    pub status: Status,
    #[doc = "STATIC"]
    pub static_: Static,
    #[doc = "TIM16"]
    pub tim16: Tim16,
    #[doc = "TIM2"]
    pub tim2: Tim2,
    #[doc = "USART"]
    pub usart: Usart,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        DEVICE_PERIPHERALS = true;
        Peripherals {
            adc: Adc::steal(),
            aes: Aes::steal(),
            crc: Crc::steal(),
            comp: Comp::steal(),
            dac: Dac::steal(),
            dbgmcu: Dbgmcu::steal(),
            dmamux: Dmamux::steal(),
            dma: Dma::steal(),
            dynamic_reg: DynamicReg::steal(),
            flash_ctrl: FlashCtrl::steal(),
            gpioa: Gpioa::steal(),
            gpiob: Gpiob::steal(),
            i2c1: I2c1::steal(),
            i2c2: I2c2::steal(),
            iwdg: Iwdg::steal(),
            lcd: Lcd::steal(),
            lpuart: Lpuart::steal(),
            lcsc: Lcsc::steal(),
            lpawur: Lpawur::steal(),
            misc: Misc::steal(),
            mr_subg: MrSubg::steal(),
            pwrc: Pwrc::steal(),
            rcc: Rcc::steal(),
            retained: Retained::steal(),
            rng: Rng::steal(),
            rtc: Rtc::steal(),
            spi: Spi::steal(),
            spi3: Spi3::steal(),
            system_ctrl: SystemCtrl::steal(),
            switchable: Switchable::steal(),
            status: Status::steal(),
            static_: Static::steal(),
            tim16: Tim16::steal(),
            tim2: Tim2::steal(),
            usart: Usart::steal(),
        }
    }
}
