#[doc = "Register `CONF` reader"]
pub type R = crate::R<ConfSpec>;
#[doc = "Register `CONF` writer"]
pub type W = crate::W<ConfSpec>;
#[doc = "Field `CONT` reader - CONT: regular sequence runs continuously when ADC mode is enabled: 0: enable the single conversion: when the sequence is over, the conversion stops 1: enable the continuous conversion: when the sequence is over, the sequence starts again until the software sets the CTRL.STOP_OP_MODE bit."]
pub type ContR = crate::BitReader;
#[doc = "Field `CONT` writer - CONT: regular sequence runs continuously when ADC mode is enabled: 0: enable the single conversion: when the sequence is over, the conversion stops 1: enable the continuous conversion: when the sequence is over, the sequence starts again until the software sets the CTRL.STOP_OP_MODE bit."]
pub type ContW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SEQUENCE` reader - SEQUENCE: enable the sequence mode (active by default): 0: sequence mode is disabled, only SEQ0 is selected 1: sequence mode is enabled, conversions from SEQ0 to SEQx with x=SEQ_LEN Note: clearing this bit is equivalent to SEQUENCE=1 and SEQ_LEN=0000. Ideally, this bit can be kept high as redundant with keeping high and setting SEQ_LEN=0000."]
pub type SequenceR = crate::BitReader;
#[doc = "Field `SEQUENCE` writer - SEQUENCE: enable the sequence mode (active by default): 0: sequence mode is disabled, only SEQ0 is selected 1: sequence mode is enabled, conversions from SEQ0 to SEQx with x=SEQ_LEN Note: clearing this bit is equivalent to SEQUENCE=1 and SEQ_LEN=0000. Ideally, this bit can be kept high as redundant with keeping high and setting SEQ_LEN=0000."]
pub type SequenceW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SEQ_LEN` reader - SEQ_LEN\\[3:0\\]: number of conversions in a regular sequence: 0000: 1 conversion, starting from SEQ0 0001: 2 conversions, starting from SEQ0 ... 1111: 16 conversions, starting from SEQ0"]
pub type SeqLenR = crate::FieldReader;
#[doc = "Field `SEQ_LEN` writer - SEQ_LEN\\[3:0\\]: number of conversions in a regular sequence: 0000: 1 conversion, starting from SEQ0 0001: 2 conversions, starting from SEQ0 ... 1111: 16 conversions, starting from SEQ0"]
pub type SeqLenW<'a, REG> = crate::FieldWriter<'a, REG, 4>;
#[doc = "Field `SMPS_SYNCHRO_ENA` reader - SMPS_SYNCHRO_ENA: synchronize the ADC start conversion with a pulse generated by the SMPS: 0: SMPS synchronization is disabled for all ADC clock frequencies 1: SMPS synchronization is enabled (only when ADC clock is 8 MHz or 16 MHz) Note: SMPS_SYNCHRO_ENA must be 0 when the ADC analog clock is 32 MHz or when PWRC_CR5.NOSMPS = 1."]
pub type SmpsSynchroEnaR = crate::BitReader;
#[doc = "Field `SMPS_SYNCHRO_ENA` writer - SMPS_SYNCHRO_ENA: synchronize the ADC start conversion with a pulse generated by the SMPS: 0: SMPS synchronization is disabled for all ADC clock frequencies 1: SMPS synchronization is enabled (only when ADC clock is 8 MHz or 16 MHz) Note: SMPS_SYNCHRO_ENA must be 0 when the ADC analog clock is 32 MHz or when PWRC_CR5.NOSMPS = 1."]
pub type SmpsSynchroEnaW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SAMPLE_RATE_LSB` reader - SAMPLE_RATE_LSB: Sample Rate LSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description. When this field is set to a value different than 0, SMPS synchronization is not feasible. This value is hidden to the user"]
pub type SampleRateLsbR = crate::FieldReader;
#[doc = "Field `SAMPLE_RATE_LSB` writer - SAMPLE_RATE_LSB: Sample Rate LSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description. When this field is set to a value different than 0, SMPS synchronization is not feasible. This value is hidden to the user"]
pub type SampleRateLsbW<'a, REG> = crate::FieldWriter<'a, REG, 2>;
#[doc = "Field `SAMPLE_RATE` reader - SAMPLE_RATE\\[1:0\\]: conversion rate of ADC (F_ADC): F_ADC = F_ADC_CLK/(16 + 16*SAMPLE_RATE_MSB + 4*SAMPLE_RATE + SAMPLE_RATE_LSB),where F_ADC_CLK is the analog ADC clock frequency. By default F_ADC_CLK is 16MHz frequency."]
pub type SampleRateR = crate::FieldReader;
#[doc = "Field `SAMPLE_RATE` writer - SAMPLE_RATE\\[1:0\\]: conversion rate of ADC (F_ADC): F_ADC = F_ADC_CLK/(16 + 16*SAMPLE_RATE_MSB + 4*SAMPLE_RATE + SAMPLE_RATE_LSB),where F_ADC_CLK is the analog ADC clock frequency. By default F_ADC_CLK is 16MHz frequency."]
pub type SampleRateW<'a, REG> = crate::FieldWriter<'a, REG, 2>;
#[doc = "Field `DMA_DS_ENA` reader - DMA_DS_EN: enable the DMA mode for the Down Sampler data path: 0: DMA mode is disabled 1: DMA mode is enabled"]
pub type DmaDsEnaR = crate::BitReader;
#[doc = "Field `DMA_DS_ENA` writer - DMA_DS_EN: enable the DMA mode for the Down Sampler data path: 0: DMA mode is disabled 1: DMA mode is enabled"]
pub type DmaDsEnaW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `OVR_DS_CFG` reader - OVR_DS_CFG: Down Sampler overrun configuration: 0: the previous data is kept, the new one is lost 1: the previous data is lost, the new one is kept"]
pub type OvrDsCfgR = crate::BitReader;
#[doc = "Field `OVR_DS_CFG` writer - OVR_DS_CFG: Down Sampler overrun configuration: 0: the previous data is kept, the new one is lost 1: the previous data is lost, the new one is kept"]
pub type OvrDsCfgW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `BIT_INVERT_SN` reader - BIT_INVERT_SN: invert bit to bit the ADC data output (1's complement) when a single negative input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
pub type BitInvertSnR = crate::BitReader;
#[doc = "Field `BIT_INVERT_SN` writer - BIT_INVERT_SN: invert bit to bit the ADC data output (1's complement) when a single negative input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
pub type BitInvertSnW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `BIT_INVERT_DIFF` reader - BIT_INVERT_DIFF: invert bit to bit the ADC data output (1's complement) when a differential input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
pub type BitInvertDiffR = crate::BitReader;
#[doc = "Field `BIT_INVERT_DIFF` writer - BIT_INVERT_DIFF: invert bit to bit the ADC data output (1's complement) when a differential input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
pub type BitInvertDiffW<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `ADC_CONT_1V2` reader - ADC_CONT_1V2: select the input sampling method: 0: sampling only at conversion start (default) 1: sampling starts at the end of conversion"]
pub type AdcCont1v2R = crate::BitReader;
#[doc = "Field `ADC_CONT_1V2` writer - ADC_CONT_1V2: select the input sampling method: 0: sampling only at conversion start (default) 1: sampling starts at the end of conversion"]
pub type AdcCont1v2W<'a, REG> = crate::BitWriter<'a, REG>;
#[doc = "Field `SAMPLE_RATE_MSB` reader - SAMPLE_RATE_MSB: Sample Rate MSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description"]
pub type SampleRateMsbR = crate::FieldReader;
#[doc = "Field `SAMPLE_RATE_MSB` writer - SAMPLE_RATE_MSB: Sample Rate MSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description"]
pub type SampleRateMsbW<'a, REG> = crate::FieldWriter<'a, REG, 3>;
impl R {
    #[doc = "Bit 0 - CONT: regular sequence runs continuously when ADC mode is enabled: 0: enable the single conversion: when the sequence is over, the conversion stops 1: enable the continuous conversion: when the sequence is over, the sequence starts again until the software sets the CTRL.STOP_OP_MODE bit."]
    #[inline(always)]
    pub fn cont(&self) -> ContR {
        ContR::new((self.bits & 1) != 0)
    }
    #[doc = "Bit 1 - SEQUENCE: enable the sequence mode (active by default): 0: sequence mode is disabled, only SEQ0 is selected 1: sequence mode is enabled, conversions from SEQ0 to SEQx with x=SEQ_LEN Note: clearing this bit is equivalent to SEQUENCE=1 and SEQ_LEN=0000. Ideally, this bit can be kept high as redundant with keeping high and setting SEQ_LEN=0000."]
    #[inline(always)]
    pub fn sequence(&self) -> SequenceR {
        SequenceR::new(((self.bits >> 1) & 1) != 0)
    }
    #[doc = "Bits 2:5 - SEQ_LEN\\[3:0\\]: number of conversions in a regular sequence: 0000: 1 conversion, starting from SEQ0 0001: 2 conversions, starting from SEQ0 ... 1111: 16 conversions, starting from SEQ0"]
    #[inline(always)]
    pub fn seq_len(&self) -> SeqLenR {
        SeqLenR::new(((self.bits >> 2) & 0x0f) as u8)
    }
    #[doc = "Bit 6 - SMPS_SYNCHRO_ENA: synchronize the ADC start conversion with a pulse generated by the SMPS: 0: SMPS synchronization is disabled for all ADC clock frequencies 1: SMPS synchronization is enabled (only when ADC clock is 8 MHz or 16 MHz) Note: SMPS_SYNCHRO_ENA must be 0 when the ADC analog clock is 32 MHz or when PWRC_CR5.NOSMPS = 1."]
    #[inline(always)]
    pub fn smps_synchro_ena(&self) -> SmpsSynchroEnaR {
        SmpsSynchroEnaR::new(((self.bits >> 6) & 1) != 0)
    }
    #[doc = "Bits 9:10 - SAMPLE_RATE_LSB: Sample Rate LSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description. When this field is set to a value different than 0, SMPS synchronization is not feasible. This value is hidden to the user"]
    #[inline(always)]
    pub fn sample_rate_lsb(&self) -> SampleRateLsbR {
        SampleRateLsbR::new(((self.bits >> 9) & 3) as u8)
    }
    #[doc = "Bits 11:12 - SAMPLE_RATE\\[1:0\\]: conversion rate of ADC (F_ADC): F_ADC = F_ADC_CLK/(16 + 16*SAMPLE_RATE_MSB + 4*SAMPLE_RATE + SAMPLE_RATE_LSB),where F_ADC_CLK is the analog ADC clock frequency. By default F_ADC_CLK is 16MHz frequency."]
    #[inline(always)]
    pub fn sample_rate(&self) -> SampleRateR {
        SampleRateR::new(((self.bits >> 11) & 3) as u8)
    }
    #[doc = "Bit 13 - DMA_DS_EN: enable the DMA mode for the Down Sampler data path: 0: DMA mode is disabled 1: DMA mode is enabled"]
    #[inline(always)]
    pub fn dma_ds_ena(&self) -> DmaDsEnaR {
        DmaDsEnaR::new(((self.bits >> 13) & 1) != 0)
    }
    #[doc = "Bit 15 - OVR_DS_CFG: Down Sampler overrun configuration: 0: the previous data is kept, the new one is lost 1: the previous data is lost, the new one is kept"]
    #[inline(always)]
    pub fn ovr_ds_cfg(&self) -> OvrDsCfgR {
        OvrDsCfgR::new(((self.bits >> 15) & 1) != 0)
    }
    #[doc = "Bit 17 - BIT_INVERT_SN: invert bit to bit the ADC data output (1's complement) when a single negative input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
    #[inline(always)]
    pub fn bit_invert_sn(&self) -> BitInvertSnR {
        BitInvertSnR::new(((self.bits >> 17) & 1) != 0)
    }
    #[doc = "Bit 18 - BIT_INVERT_DIFF: invert bit to bit the ADC data output (1's complement) when a differential input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
    #[inline(always)]
    pub fn bit_invert_diff(&self) -> BitInvertDiffR {
        BitInvertDiffR::new(((self.bits >> 18) & 1) != 0)
    }
    #[doc = "Bit 19 - ADC_CONT_1V2: select the input sampling method: 0: sampling only at conversion start (default) 1: sampling starts at the end of conversion"]
    #[inline(always)]
    pub fn adc_cont_1v2(&self) -> AdcCont1v2R {
        AdcCont1v2R::new(((self.bits >> 19) & 1) != 0)
    }
    #[doc = "Bits 21:23 - SAMPLE_RATE_MSB: Sample Rate MSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description"]
    #[inline(always)]
    pub fn sample_rate_msb(&self) -> SampleRateMsbR {
        SampleRateMsbR::new(((self.bits >> 21) & 7) as u8)
    }
}
impl W {
    #[doc = "Bit 0 - CONT: regular sequence runs continuously when ADC mode is enabled: 0: enable the single conversion: when the sequence is over, the conversion stops 1: enable the continuous conversion: when the sequence is over, the sequence starts again until the software sets the CTRL.STOP_OP_MODE bit."]
    #[inline(always)]
    pub fn cont(&mut self) -> ContW<'_, ConfSpec> {
        ContW::new(self, 0)
    }
    #[doc = "Bit 1 - SEQUENCE: enable the sequence mode (active by default): 0: sequence mode is disabled, only SEQ0 is selected 1: sequence mode is enabled, conversions from SEQ0 to SEQx with x=SEQ_LEN Note: clearing this bit is equivalent to SEQUENCE=1 and SEQ_LEN=0000. Ideally, this bit can be kept high as redundant with keeping high and setting SEQ_LEN=0000."]
    #[inline(always)]
    pub fn sequence(&mut self) -> SequenceW<'_, ConfSpec> {
        SequenceW::new(self, 1)
    }
    #[doc = "Bits 2:5 - SEQ_LEN\\[3:0\\]: number of conversions in a regular sequence: 0000: 1 conversion, starting from SEQ0 0001: 2 conversions, starting from SEQ0 ... 1111: 16 conversions, starting from SEQ0"]
    #[inline(always)]
    pub fn seq_len(&mut self) -> SeqLenW<'_, ConfSpec> {
        SeqLenW::new(self, 2)
    }
    #[doc = "Bit 6 - SMPS_SYNCHRO_ENA: synchronize the ADC start conversion with a pulse generated by the SMPS: 0: SMPS synchronization is disabled for all ADC clock frequencies 1: SMPS synchronization is enabled (only when ADC clock is 8 MHz or 16 MHz) Note: SMPS_SYNCHRO_ENA must be 0 when the ADC analog clock is 32 MHz or when PWRC_CR5.NOSMPS = 1."]
    #[inline(always)]
    pub fn smps_synchro_ena(&mut self) -> SmpsSynchroEnaW<'_, ConfSpec> {
        SmpsSynchroEnaW::new(self, 6)
    }
    #[doc = "Bits 9:10 - SAMPLE_RATE_LSB: Sample Rate LSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description. When this field is set to a value different than 0, SMPS synchronization is not feasible. This value is hidden to the user"]
    #[inline(always)]
    pub fn sample_rate_lsb(&mut self) -> SampleRateLsbW<'_, ConfSpec> {
        SampleRateLsbW::new(self, 9)
    }
    #[doc = "Bits 11:12 - SAMPLE_RATE\\[1:0\\]: conversion rate of ADC (F_ADC): F_ADC = F_ADC_CLK/(16 + 16*SAMPLE_RATE_MSB + 4*SAMPLE_RATE + SAMPLE_RATE_LSB),where F_ADC_CLK is the analog ADC clock frequency. By default F_ADC_CLK is 16MHz frequency."]
    #[inline(always)]
    pub fn sample_rate(&mut self) -> SampleRateW<'_, ConfSpec> {
        SampleRateW::new(self, 11)
    }
    #[doc = "Bit 13 - DMA_DS_EN: enable the DMA mode for the Down Sampler data path: 0: DMA mode is disabled 1: DMA mode is enabled"]
    #[inline(always)]
    pub fn dma_ds_ena(&mut self) -> DmaDsEnaW<'_, ConfSpec> {
        DmaDsEnaW::new(self, 13)
    }
    #[doc = "Bit 15 - OVR_DS_CFG: Down Sampler overrun configuration: 0: the previous data is kept, the new one is lost 1: the previous data is lost, the new one is kept"]
    #[inline(always)]
    pub fn ovr_ds_cfg(&mut self) -> OvrDsCfgW<'_, ConfSpec> {
        OvrDsCfgW::new(self, 15)
    }
    #[doc = "Bit 17 - BIT_INVERT_SN: invert bit to bit the ADC data output (1's complement) when a single negative input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
    #[inline(always)]
    pub fn bit_invert_sn(&mut self) -> BitInvertSnW<'_, ConfSpec> {
        BitInvertSnW::new(self, 17)
    }
    #[doc = "Bit 18 - BIT_INVERT_DIFF: invert bit to bit the ADC data output (1's complement) when a differential input is connected to the ADC: 0: no inversion (default) 1: enable the inversion"]
    #[inline(always)]
    pub fn bit_invert_diff(&mut self) -> BitInvertDiffW<'_, ConfSpec> {
        BitInvertDiffW::new(self, 18)
    }
    #[doc = "Bit 19 - ADC_CONT_1V2: select the input sampling method: 0: sampling only at conversion start (default) 1: sampling starts at the end of conversion"]
    #[inline(always)]
    pub fn adc_cont_1v2(&mut self) -> AdcCont1v2W<'_, ConfSpec> {
        AdcCont1v2W::new(self, 19)
    }
    #[doc = "Bits 21:23 - SAMPLE_RATE_MSB: Sample Rate MSB This field is an extension of SAMPLE_RATE definition in bits 12,11 of CONF register. It impacts the conversion rate of ADC (F_ADC). See SAMPLE_RATE bits for the full description"]
    #[inline(always)]
    pub fn sample_rate_msb(&mut self) -> SampleRateMsbW<'_, ConfSpec> {
        SampleRateMsbW::new(self, 21)
    }
}
#[doc = "CONF register\n\nYou can [`read`](crate::Reg::read) this register and get [`conf::R`](R). You can [`reset`](crate::Reg::reset), [`write`](crate::Reg::write), [`write_with_zero`](crate::Reg::write_with_zero) this register using [`conf::W`](W). You can also [`modify`](crate::Reg::modify) this register. See [API](https://docs.rs/svd2rust/#read--modify--write-api)."]
pub struct ConfSpec;
impl crate::RegisterSpec for ConfSpec {
    type Ux = u32;
}
#[doc = "`read()` method returns [`conf::R`](R) reader structure"]
impl crate::Readable for ConfSpec {}
#[doc = "`write(|w| ..)` method takes [`conf::W`](W) writer structure"]
impl crate::Writable for ConfSpec {
    type Safety = crate::Unsafe;
}
#[doc = "`reset()` method sets CONF to value 0x0002_0002"]
impl crate::Resettable for ConfSpec {
    const RESET_VALUE: u32 = 0x0002_0002;
}
